language: fortran

sudo: required

services:
  - docker

env:
 - TEST_SUITE=RTI-LST/test_fft.py
 - TEST_SUITE=RTI-LST/test_asym.py
 - TEST_SUITE=RTI-LST/test_nonuniform.py
 - TEST_SUITE=RTI-LST/test_bound.py
 - TEST_SUITE=RTI-LST/test_restart.py
 - TEST_SUITE=RTI-LST/test_restart_long.py
 - TEST_SUITE=lid/test_lid.py
 - TEST_SUITE=iturb/test_iturb.py
 - TEST_SUITE=iturb/test_courant.py
 - TEST_SUITE=Hill/test_Hill.py
 - TEST_SUITE=duct/test_duct.py
 - TEST_SUITE=corner/test_corner.py
 - TEST_SUITE=eddy/test_eddy.py
 - TEST_SUITE=eddy/test_bdf2.py
 - TEST_SUITE=eddy/test_bdf3.py
 - TEST_SUITE=eddy/test_bdf4.py

before_install: 
 - docker pull maxhutch/nekbox-tester

script: 
 - if [[ "$TRAVIS_PULL_REQUEST" -eq "false" ]]; then docker run -v `pwd`:/home/nek/NekBox maxhutch/nekbox-tester -m "not pr" $TEST_SUITE; else docker run -v `pwd`:/home/nek/NekBox maxhutch/nekbox-tester $TEST_SUITE; fi
